# Generated by Django 5.1.7 on 2025-03-23 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_player", models.CharField(default="X", max_length=1)),
                (
                    "board",
                    models.TextField(
                        default='[["", "", ""], ["", "", ""], ["", "", ""]]'
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("draw", "Draw"),
                            ("waiting", "Waiting for Player"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("winner", models.CharField(blank=True, max_length=1, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_o",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_o",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_x",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_x",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
